### ISSUE TITLE
message keys and properties

### ISSUE THREAD

**Issue by rafalg** [micronaut-projects/micronaut-pulsar#101]
### Feature description

Hi,

I'm interested in adding support for keys and msg properties in producer api. Thinking about doing it in a similar way as in micronaut-kafka integration. Anyone interested?

Cheers,

**Comment by harissecic** [comment]
You are very welcome to make a pull request for any contribution. 

However if I'm not mistaking you'll like to have something like `@KafkaKey` for Pulsar? This is a bit tricky as Pulsar works quite differently from Kafka. However I started a rewrite of Serialization which avoids some reflection that underlying Pulsar library uses and you can start there. There is a line in SchemaResolver.java in a long switch statement. From there you would have to implement Key-Value serialization for JSON, byte[], Avro, and others. 

Also I'm not sure what you mean by message properties. Producers are created using Pulsar library and offer only MessageId on sending.  Maybe I'm missing the point and don't really understand what you intended to do?

**Comment by rafalg** [comment]
Hi Harris,

Properties are equivalent to the kafka headers. These can be attached https://pulsar.apache.org/api/client/2.8.0-SNAPSHOT/org/apache/pulsar/client/api/TypedMessageBuilder.html#properties-java.util.Map- while constructing a new message. In fact this is a feature that I need the most.  Micronaut-kafka does this via KafkaHeader annotation. If a producer method has a parameter with such an annotation it's value is added to the message headers. 
`void sendProduct(
    String name,
    @MessageHeader("My-Header") String myHeader);`
Would like to implement it in a similar fashon here. By looking at micronaut-pulsar source the key place to focus in PulsarProducerAdvice. Would need to switch to use pulsar's TypedMessageBuilder instead of send[Async] directly from producer api in the first place. Then add a support for a new annotation. 
Keys are of secondary intrest for now for me.
What do you think?

**Comment by harissecic** [comment]
> Hi Haris,
> 
> Properties are equivalent to the kafka headers. These can be attached https://pulsar.apache.org/api/client/2.8.0-SNAPSHOT/org/apache/pulsar/client/api/TypedMessageBuilder.html#properties-java.util.Map- while constructing a new message. In fact this is a feature that I need the most. Micronaut-kafka does this via KafkaHeader annotation. If a producer method has a parameter with such an annotation it's value is added to the message headers.
> `void sendProduct( String name, @MessageHeader("My-Header") String myHeader);`
> Would like to implement it in a similar fashon here. By looking at micronaut-pulsar source the key place to focus in PulsarProducerAdvice. Would need to switch to use pulsar's TypedMessageBuilder instead of send[Async] directly from producer api in the first place. Then add a support for a new annotation.
> Keys are of secondary intrest for now for me.
> What do you think?
Sure, sounds "fun". And yes PulsarAdvice would be the place to handle headers. Key-Values are a bit complicated due to previous explanation - in fact it's just time consuming not complicated. Just keep in mind that test may work locally for you but when pushing to GitHub it might break. I'm working on it to try to fix Kotlin randomly appearing issues as well as to figure out why would locally work and GitHub has issues (tested all versions). In any case if tests are passing locally I would probably even merge it to main branch.
Thanks, hope we get this more stable and up to RELEASE version soon.

**Comment by rafalg** [comment]
Hi,

Sure. Will wrestle with it a bit over the weekend. 
Having a first release would be a great milestone as well ;)

**Comment by harissecic** [comment]
> Hi,
> 
> Sure. Will wrestle with it a bit over the weekend. Having a first release would be a great milestone as well ;)

Hi, sorry but I had to clean up examples and give up on Kotlin full example as it uses at least 7.9GB memory which leads to crash of daemon in GitHub actions. Also doc-examples are renamed and properly put now as just documentation references. Documentations are updated to reflect changes but more importantly to contain the proper 3 version of code (Java, Groovy, Kotlin). Hope it didn't disturb your work too much. In case you haven't started that's also good and I could take a look at it as well.

**Comment by rafalg** [comment]
Hi Haris,

Got the producer side sorted. Will try to push it on Monday/Tuesday depending on my spare time.
Decided to use MessageHeader annotation that is part of generic micronaut-messaging package instead of
declaring new pulsar specific one. 
Got a bit puzzled with the consumer side as it uses some Kotlin stuff that I'm not that familiar with.

See you soon on a PR with producer part!

**Comment by harissecic** [comment]
I was planning on trying to implement `@SendTo` support. This would directly affect your changes. If you want feel free to make a pull request with your changes then I can jump in and make them in that branch. Let me know otherwise.

**Comment by harissecic** [comment]
@rafalg I've decided to give it a go https://github.com/micronaut-projects/micronaut-pulsar/pull/144. Docs will be generated so you can check the usage there. In short this pull request will contain parsing `@MessageProperties` with argument `Map<String,String>` for both consumers and producers in case you want to read all properties. Also it will allow `@MessaageHeader("headerName")` for a per-argument header approach - of course only String since Pulsar lib wants that.

On the other hand main point was `@MessageKey` for keys (on both producer and the consumer) and now you need to use `@MessageBody` on a body in case you have multiple method arguments.

Let me know what you think, otherwise I'll soon merge that pull request
